Make relationship between Club & User - manager #29
team-blackhole/UNIST-group-list-backend pull request #30
Opened 2018-02-13 11:30 UTC by mango-tree

ManyToMany 예시입니다. (Club manager로 User와 Club을 연결)

2018-02-18 11:22 UTC, mango-tree commented
@pelly-ryu 확인해주세욧

2018-02-23 09:32 UTC, pelly-ryu requested changes

2018-02-23 09:32 UTC, pelly-ryu commented on app/auth/models.py
> +    def get_managingClubs_list(self):
identifier 파이썬처럼 해주세용

2018-02-23 09:32 UTC, pelly-ryu commented on app/auth/models.py
> +    managingClubs = db.relationship('Club', secondary=manager)
여기 camelCase밖에 못쓰나여??

2018-02-23 09:32 UTC, pelly-ryu commented on app/auth/resources.py
> +    userListParser = ns.parser()
ㅠㅠ 파이썬을 지켜주세여

2018-02-23 09:32 UTC, pelly-ryu commented on app/auth/resources.py
> +    userSearchParser = ns.parser()
여기도

2018-02-23 09:32 UTC, pelly-ryu commented on app/auth/resources.py
> +    'managingClubs': fields.Raw()
오 신기.. Raw근여

2018-02-24 05:12 UTC, mango-tree commented
헉 오늘 고쳐놓을게여

2018-02-24 15:22 UTC, mango-tree commented
고쳤어용

2018-02-26 07:50 UTC, merged